name: SonarCloud Build

on:
  push:
    branches:
     - 'master'
     #- '4.0'
     #- '5.0'
     #- '5.4'
     #- '6.0'
     
  pull_request:
    types: [opened, synchronize, reopened]
jobs:

  SonarCloud-C:
    name: SonarCloud-C
    runs-on: ubuntu-latest
    env:
      SONAR_SCANNER_VERSION: 4.7.0.2747
      SONAR_SERVER_URL: "https://sonarcloud.io"
      BUILD_WRAPPER_OUT_DIR: $HOME/.sonar/build_wrapper_output_directory # Directory where build-wrapper output will be placed
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

